#!/bin/bash
unset x y
eval $(xwininfo -id $(xdotool getactivewindow) |
    sed -n -e "s/^ \+Absolute upper-left X: \+\([0-9]\+\).*/x=\1/p" \
    -e "s/^ \+Absolute upper-left Y: \+\([0-9]\+\).*/y=\1/p" )

direction=$1
display_height=1080
top_margin=52

if [ $direction == "up" ]; then
  y_pos=$(($y - $display_height - $top_margin))
  if [ $y_pos -ge 0 ]; then
    wmctrl -r ":ACTIVE:" -e 0,$x,$y_pos,-1,-1
  fi
fi

if [ $direction == "down" ]; then
  y_pos=$(($display_height + $y - $top_margin))
  if [ $y_pos -lt $(( 2 * $display_height )) ]; then
    wmctrl -r ":ACTIVE:" -e 0,$x,$y_pos,-1,-1
  fi
fi

